# Chapter 9: Room with planes and spheres

[camera]
width = 1000
height = 500
fov = 60
from = [0.0, 2.5, -8.0]
to = [0.0, 1.5, 0.0]
up = [0.0, 1.0, 0.0]

[light]
position = [-3.0, 4.0, 0.0]
intensity = [1.0, 1.0, 1.0]

# Floor
[[objects]]
type = "plane"

[objects.material]
color = [0.8, 0.8, 0.8]
specular = 0.1

# Ceiling
[[objects]]
type = "plane"

[objects.transform]
translate = [0.0, 5.0, 0.0]

[objects.material]
color = [0.9, 0.9, 0.95]
specular = 0.0

# Back wall
[[objects]]
type = "plane"

[objects.transform]
rotate_x = 90.0
translate = [0.0, 0.0, 5.0]

[objects.material]
color = [0.7, 0.8, 0.9]
specular = 0.0

# Left wall
[[objects]]
type = "plane"

[objects.transform]
rotate_z = 90.0
translate = [-5.0, 0.0, 0.0]

[objects.material]
color = [0.9, 0.7, 0.7]
specular = 0.0

# Right wall
[[objects]]
type = "plane"

[objects.transform]
rotate_z = -90.0
translate = [5.0, 0.0, 0.0]

[objects.material]
color = [0.7, 0.9, 0.7]
specular = 0.0

# Large sphere
[[objects]]
type = "sphere"

[objects.transform]
translate = [-0.5, 1.0, 0.5]

[objects.material]
color = [0.1, 0.5, 0.1]
diffuse = 0.7
specular = 0.3

# Medium sphere
[[objects]]
type = "sphere"

[objects.transform]
scale = [0.75, 0.75, 0.75]
translate = [1.5, 0.75, 0.0]

[objects.material]
color = [0.2, 0.8, 0.2]
diffuse = 0.7
specular = 0.3

# Small sphere
[[objects]]
type = "sphere"

[objects.transform]
scale = [0.4, 0.4, 0.4]
translate = [-1.8, 0.4, -0.3]

[objects.material]
color = [1.0, 0.9, 0.2]
diffuse = 0.7
specular = 0.3
