# Chapter 13: Rocket Scene
# Demonstrates cones, cylinders, and cubes building a simple rocket

[camera]
width = 800
height = 600
fov = 60
from = [0.0, 4.0, -12.0]
to = [0.0, 3.0, 0.0]
up = [0.0, 1.0, 0.0]

[light]
position = [-10.0, 15.0, -10.0]
intensity = [1.0, 1.0, 1.0]

# Ground plane
[[objects]]
type = "plane"

[objects.material]
color = [0.2, 0.18, 0.16]
ambient = 0.25
diffuse = 0.5
specular = 0.0

# Launch pad
[[objects]]
type = "cube"

[objects.transform]
scale = [3.0, 0.25, 3.0]
translate = [0.0, 0.125, 0.0]

[objects.material]
color = [0.55, 0.55, 0.6]
ambient = 0.25
diffuse = 0.6
specular = 0.2
shininess = 80.0

# Rocket body (white cylinder)
[[objects]]
type = "cylinder"
minimum = 0.0
maximum = 1.0
closed = true

[objects.transform]
scale = [1.0, 3.6, 1.0]
translate = [0.0, 0.375, 0.0]

[objects.material]
color = [0.85, 0.85, 0.9]
ambient = 0.1
diffuse = 0.7
specular = 0.4
shininess = 120.0

# Rocket nose cone (red)
[[objects]]
type = "cone"
minimum = 0.0
maximum = 1.0
closed = true

[objects.transform]
scale = [1.2, 1.3, 1.2]
translate = [0.0, 5.1, 0.0]
rotate_x = 180.0


[objects.material]
color = [0.92, 0.22, 0.22]
ambient = 0.1
diffuse = 0.7
specular = 0.5
shininess = 150.0

# Left fin
[[objects]]
type = "cube"

[objects.transform]
scale = [0.15, 0.8, 0.5]
rotate_z = -25.0
translate = [-1.1, 0.5, 0.5]

[objects.material]
color = [0.95, 0.55, 0.25]
ambient = 0.2
diffuse = 0.6
specular = 0.2
shininess = 80.0

# Right fin
[[objects]]
type = "cube"

[objects.transform]
scale = [0.15, 0.8, 0.5]
rotate_z = 25.0
translate = [1.1, 0.5, 0.5]

[objects.material]
color = [0.95, 0.55, 0.25]
ambient = 0.2
diffuse = 0.6
specular = 0.2
shininess = 80.0

# Rear fin
[[objects]]
type = "cube"

[objects.transform]
scale = [0.15, 0.8, 0.5]
rotate_x = -65.0
translate = [0.0, 0.5, -1.1]

[objects.material]
color = [0.95, 0.55, 0.25]
ambient = 0.2
diffuse = 0.6
specular = 0.2
shininess = 80.180
