# Chapter 11: Reflection and Refraction Showcase
# Demonstrates reflective, refractive, and combined materials

[camera]
width = 800
height = 600
fov = 60
from = [0.0, 1.5, -5.0]
to = [0.0, 1.0, 0.0]
up = [0.0, 1.0, 0.0]

[light]
position = [-10.0, 10.0, -10.0]
intensity = [1.0, 1.0, 1.0]

# Reflective floor with transparency - shows both reflection and refraction
[[objects]]
type = "plane"

[objects.material]
ambient = 0.05
diffuse = 0.4
specular = 0.9
shininess = 300.0
reflectivity = 0.4
transparency = 0.3
refractive_index = 1.5

[objects.material.pattern]
type = "checkers"
color_a = [0.15, 0.15, 0.15]
color_b = [0.85, 0.85, 0.85]

# Large glass sphere - highly transparent with some reflection (Fresnel effect via Schlick)
[[objects]]
type = "sphere"

[objects.transform]
translate = [-1.5, 1.0, 0.5]

[objects.material]
color = [0.9, 0.9, 1.0]
ambient = 0.0
diffuse = 0.1
specular = 0.9
shininess = 300.0
reflectivity = 0.9
transparency = 0.9
refractive_index = 1.5

# Crystal ball - pure glass
[[objects]]
type = "sphere"

[objects.transform]
scale = [0.7, 0.7, 0.7]
translate = [0.5, 0.7, -0.5]

[objects.material]
color = [1.0, 1.0, 1.0]
ambient = 0.0
diffuse = 0.0
specular = 0.9
shininess = 300.0
reflectivity = 0.9
transparency = 1.0
refractive_index = 1.5

# Small red sphere behind glass spheres - to see refraction
[[objects]]
type = "sphere"

[objects.transform]
scale = [0.5, 0.5, 0.5]
translate = [2.0, 0.5, 1.0]

[objects.material]
color = [1.0, 0.2, 0.2]
ambient = 0.2
diffuse = 0.7
specular = 0.3
shininess = 200.0
reflectivity = 0.0

# Small green sphere - partially reflective and transparent
[[objects]]
type = "sphere"

[objects.transform]
scale = [0.6, 0.6, 0.6]
translate = [-0.5, 0.6, -2.0]

[objects.material]
color = [0.2, 1.0, 0.2]
ambient = 0.1
diffuse = 0.6
specular = 0.4
shininess = 200.0
reflectivity = 0.5
transparency = 0.5
refractive_index = 1.5

# Small blue mirror sphere - highly reflective, no transparency
[[objects]]
type = "sphere"

[objects.transform]
scale = [0.5, 0.5, 0.5]
translate = [1.5, 0.5, -1.5]

[objects.material]
color = [0.2, 0.2, 1.0]
ambient = 0.0
diffuse = 0.2
specular = 0.9
shininess = 300.0
reflectivity = 0.9
transparency = 0.0

# Floating glass bubble - thin shell effect with high transparency
[[objects]]
type = "sphere"

[objects.transform]
scale = [0.4, 0.4, 0.4]
translate = [-2.5, 0.4, -0.5]

[objects.material]
color = [1.0, 1.0, 1.0]
ambient = 0.0
diffuse = 0.0
specular = 1.0
shininess = 300.0
reflectivity = 0.8
transparency = 0.95
refractive_index = 1.0
