# Chapter 12: Room Corner Scene
# Demonstrates cubes with reflective and refractive materials

[camera]
width = 800
height = 600
fov = 70
from = [-3.5, 1.8, -3.5]
to = [2.0, 1.0, 2.0]
up = [0.0, 1.0, 0.0]

[light]
position = [2.0, 5.0, -2.0]
intensity = [1.0, 1.0, 1.0]

# Floor - reflective dark and light grey checkerboard
[[objects]]
type = "plane"

[objects.material]
ambient = 0.05
diffuse = 0.4
specular = 0.9
shininess = 300.0
reflectivity = 0.15

[objects.material.pattern]
type = "checkers"
color_a = [0.2, 0.2, 0.2]
color_b = [0.8, 0.8, 0.8]

# Left wall (vertical, brown stripes)
[[objects]]
type = "plane"

[objects.transform]
rotate_z = 90.0
translate = [6.0, 0.0, 0.0]

[objects.material]
ambient = 0.2
diffuse = 0.6
specular = 0.1

[objects.material.pattern]
type = "stripe"
color_a = [0.4, 0.3, 0.2]
color_b = [0.5, 0.4, 0.3]
rotate_y = 90
scale = [0.3, 1.0, 1.0]

# Right wall (vertical, brown stripes)
[[objects]]
type = "plane"

[objects.transform]
rotate_x = 90
translate = [0.0, 0.0, 5.0]

[objects.material]
ambient = 0.2
diffuse = 0.6
specular = 0.1

[objects.material.pattern]
type = "stripe"
color_a = [0.4, 0.3, 0.2]
color_b = [0.5, 0.4, 0.3]
scale = [0.3, 1.0, 1.0]

# Mirror on left wall - highly reflective long cube
[[objects]]
type = "cube"

[objects.transform]
translate = [5.9, 2.0, 1.5]
scale = [0.05, 1.2, 2.0]

[objects.material]
color = [0.9, 0.9, 0.9]
ambient = 0.0
diffuse = 0.1
specular = 1.0
shininess = 400.0
reflectivity = 0.95

# Large red picture on right wall
[[objects]]
type = "cube"

[objects.transform]
scale = [1.2, 1.5, 0.05]
translate = [-1.5, 2.5, 4.9]

[objects.material]
color = [0.8, 0.1, 0.1]
ambient = 0.2
diffuse = 0.7
specular = 0.1

# Small green picture on right wall
[[objects]]
type = "cube"

[objects.transform]
scale = [0.5, 0.5, 0.05]
translate = [0.5, 3.5, 4.9]

[objects.material]
color = [0.1, 0.8, 0.1]
ambient = 0.2
diffuse = 0.7
specular = 0.1

# Small blue picture on right wall
[[objects]]
type = "cube"

[objects.transform]
scale = [0.4, 0.6, 0.05]
translate = [0.5, 2.3, 4.9]

[objects.material]
color = [0.1, 0.1, 0.8]
ambient = 0.2
diffuse = 0.7
specular = 0.1

# Table top - striped, mildly reflective
[[objects]]
type = "cube"

[objects.transform]
scale = [2.0, 0.08, 1.2]
translate = [0.5, 0.9, 1.5]

[objects.material]
ambient = 0.1
diffuse = 0.6
specular = 0.4
shininess = 100.0
reflectivity = 0.1

[objects.material.pattern]
type = "stripe"
color_a = [0.6, 0.5, 0.4]
color_b = [0.5, 0.4, 0.3]
scale = [0.15, 1.0, 1.0]

# Table leg 1 (front-left)
[[objects]]
type = "cube"

[objects.transform]
scale = [0.08, 0.45, 0.08]
translate = [-1.3, 0.45, 0.5]

[objects.material]
color = [0.6, 0.5, 0.4]
ambient = 0.2
diffuse = 0.7
specular = 0.1

# Table leg 2 (front-right)
[[objects]]
type = "cube"

[objects.transform]
scale = [0.08, 0.45, 0.08]
translate = [2.3, 0.45, 0.5]

[objects.material]
color = [0.6, 0.5, 0.4]
ambient = 0.2
diffuse = 0.7
specular = 0.1

# Table leg 3 (back-left)
[[objects]]
type = "cube"

[objects.transform]
scale = [0.08, 0.45, 0.08]
translate = [-1.3, 0.45, 2.5]

[objects.material]
color = [0.6, 0.5, 0.4]
ambient = 0.2
diffuse = 0.7
specular = 0.1

# Table leg 4 (back-right)
[[objects]]
type = "cube"

[objects.transform]
scale = [0.08, 0.45, 0.08]
translate = [2.3, 0.45, 2.5]

[objects.material]
color = [0.6, 0.5, 0.4]
ambient = 0.2
diffuse = 0.7
specular = 0.1

# Frosted glass cube on table - refractive and reflective
[[objects]]
type = "cube"

[objects.transform]
translate = [0.5, 1.4, 1.5]
rotate_y = -5
scale = [0.4, 0.4, 0.4]

[objects.material]
color = [1.0, 1.0, 1.0]
ambient = 0.0
diffuse = 0.2
specular = 0.9
shininess = 300.0
reflectivity = 0.5
transparency = 0.7
refractive_index = 1.5
