# Chapter 5: Simple sphere silhouette

[camera]
width = 500
height = 500
fov = 53.13  # Calculated to match original wall projection
from = [0.0, 0.0, -5.0]
to = [0.0, 0.0, 0.0]
up = [0.0, 1.0, 0.0]

[light]
position = [-10.0, 10.0, -10.0]
intensity = [1.0, 0.0, 0.0]  # Red light to create red silhouette

[[objects]]
type = "sphere"

[objects.material]
color = [1.0, 1.0, 1.0]  # White material to pick up light color
ambient = 1.0  # Full ambient for flat appearance
diffuse = 0.0
specular = 0.0
